### ISSUE TITLE
Enable previous dates

### ISSUE THREAD

**Issue by manpreetios** [bettoakkara/BACalendar#1]
Hi
I really like this library. I really appreciate your work.
But I am facing issue with disabled dates . 
how I can enable previous dates in this calendar?

Thank you
Money

**Comment by bettoakkara** [comment]
Hi,

There you can set the start date and end date 
start date would be the calendar start date. So if you are adjusting the start date might help you.   

 func showCalendar() {
        
        let calenderView = BACalenderView
        // Here we are setting delegate
        calenderView.calendarDelegate = self
        // here, you can change the theme
        calenderView.themeColor = UIColor.brown
        // here you can configure your BACalneder
        let startDate = Helper.calendarAdvanced(byAdding: .year, value: -10, startDate: Date())
        let endDate = Helper.calendarAdvanced(byAdding: .year, value: 10, startDate: Date())
        let currentSelectedDate = Date()
        calenderView.configureCalender(
            startDate: startDate,
            endDate: endDate,
            selectedDate: currentSelectedDate
        )
        
        PopupContainer.generatePopupWithView(calenderView).show()
        
    }

Thanks for the support.
